### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Zaseth** [kriszyp/msgpackr-extract#1]
Hi there. We're using your library to serialize and deserialize JSON objects. Sadly, we've encountered multiple segfaults over the past few days, causing our service to be unavailable. Here's the stack trace that I was given:

```
PID 42700 received SIGSEGV for address: 0xffffffffbb8733ad
node_modules/segfault-handler/build/Release/segfault-handler.node(+0x3216)[0x7f3b380d5216]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7f3b39ac4730]
node_modules/msgpackr-extract/build/Release/msgpackr-extract.node(+0x2f49)[0x7f3b380dbf49]
node_modules/msgpackr-extract/build/Release/msgpackr-extract.node(+0x2438)[0x7f3b380db438]
ProcessName[0x148492d]
```

Versioning:
```
└─┬ msgpackr@1.2.1
  └── msgpackr-extract@1.0.5
```

We've been using Msgpackr since `v1.0.0` and never had any issues until recently. I hope I've given you enough information to fix this issue.

**Comment by kriszyp** [comment]
Do you happen to have any guesses if it was more likely to have regressed in 1.0.2 (published 20 days ago, do you know if you used that?), or more likely to be more recent (1.0.3-1.0.5 were published 8-10 days ago)?

**Comment by Zaseth** [comment]
We first started experiencing this issue at 2 February.

**Comment by kriszyp** [comment]
Ok, I've published v1.2.3/v1.0.6 with a number of additional checks and some of optimizations reverted to attempt to address the issue. I haven't been able to directly reproduce, but hopeful that this may address it.

**Comment by Zaseth** [comment]
I'll instruct to pull the new version and I'll let keep you updated. Thanks so much!

**Comment by Zaseth** [comment]
We're now live. I'll make sure to report back with another segfault stack in case it happens again.

**Comment by Zaseth** [comment]
@kriszyp We've been running your update for a while now and we haven't seen any issues since. I'm guessing this can be closed now as fixed. Thank you so much.
