### ISSUE TITLE
Consider publishing wasm version

### ISSUE THREAD

**Issue by RDIL** [kriszyp/msgpackr-extract#10]
WebAssembly is supported in Node 8 and above, doesn't need to be compiled by the consumer, and should (I think) yield the same performance that this library does.  Can this be done or experimented with? 

Thank you in advance!

**Comment by kriszyp** [comment]
Unfortunately I don't think that will work. The performance optimization that this library provides is based on generating strings directly using NAPI functions, which are not available in WASM, at least as far as I know. WASM basically has to return buffers/binary data, which is the very thing that msgpackr is designed to (efficiently) decode. In addition, every benchmark I have seen shows WASM being a fair bit slower than native C code (that is not to say that WASM has some fantastic uses cases). Anyway, if any of this has changed, would certainly be interested.

> doesn't need to be compiled by the consumer

Hopefully this is very rare, msgpackr-extract includes binaries for every common OS/architecture that I am aware, so consumers should almost never need to actually compile anything. Let me know if you see some (reasonably common) OS/arch that is missing. Of course, the browser is main target where WASM is the only binary available, but the issues above prevent its usage for this application.

**Comment by RDIL** [comment]
Closing as this makes sense.
