### ISSUE TITLE
Recent version doesn't get compiled on macOS

### ISSUE THREAD

**Issue by vladimiry** [kriszyp/msgpackr-extract#12]
Executing Shell command (options: {"whitelistedEnv":{"DEBUG":"@electron/rebuild","MACOSX_DEPLOYMENT_TARGET":"10.10"}}): npm exec --package @electron/rebuild -- electron-rebuild --force --arch x64 --version 23.1.1 --which-module msgpackr-extract --module-dir node_modules/msgpackr-extract
```
    CXX(target) Release/obj.target/extract/src/extract.o
  ../src/extract.cpp:26:7: error: unknown type name 'uint'; did you mean 'int'?
  const uint UNEXPECTED_END = 0xffffffff;
        ^~~~
        int
  ../src/extract.cpp:147:19: warning: comparison of integers of different signs: 'uint32_t' (aka 'unsigned int') and 'const int' [-Wsign-compare]
                                          if (position == UNEXPECTED_END) {
                                              ~~~~~~~~ ^  ~~~~~~~~~~~~~~
```

https://github.com/vladimiry/ElectronMail/actions/runs/4298788953/jobs/7493748345

https://github.com/vladimiry/ElectronMail/actions/runs/4298788953/jobs/7493748458

There was no such issue with 2.2.0.

**Comment by kriszyp** [comment]
Ok, not sure how that line got in there (since it wasn't committed), but published 3.0.2 with this fixed.

**Comment by vladimiry** [comment]
Thanks. I won't be able to test it in the near future since already rolled back to 2.2.0 and triggered new CI build. But will reopen if/when I have a chance to detect it again.

**Comment by vladimiry** [comment]
Can confirm that recent version gets well compiled on macOS systems.

**Comment by kriszyp** [comment]
Thanks for checking!
