### ISSUE TITLE
Request: can you ship with prebuilt alpine binary?

### ISSUE THREAD

**Issue by gogoout** [kriszyp/msgpackr-extract#5]
Hello again, can you add the prebuilt alpine binary? It could be really useful as it's widely used in CI environment.
Also I'd like to buy you a coffee do you have any way to accept donation ?
Cheers

**Comment by kriszyp** [comment]
This should be published now in v1.0.16 with alpine binaries. Do you need an update to msgpackr to point to the newer version (fresh install should pick the latest, since this was a point release)? Anyway, thanks for the offer, I'll see if I can set something up :).

**Comment by gogoout** [comment]
Thanks, it already worked for us since we explicitly set the dependency in package.json. Thanks for the quick response.
