### ISSUE TITLE
The remote archive doesn't match the expected checksum

### ISSUE THREAD

**Issue by dustin-rcg** [kriszyp/msgpackr-extract#8]
YN0018: │ node-gyp-build@https://github.com/kriszyp/node-gyp-build.git#commit=c9952cb77e89d2cd8b6c2d4d056a06d41834b305: The remote archive doesn't match the expected checksum

yarn why node-gyp-build -R

   └─ bullmq@npm:1.77.1 (via npm:1.77.1)
      └─ msgpackr@npm:1.5.5 (via npm:^1.4.6)
         └─ msgpackr-extract@npm:1.1.0 (via npm:^1.0.14)
            └─ node-gyp-build@https://github.com/kriszyp/node-gyp-build.git#commit=c9952cb77e89d2cd8b6c2d4d056a06d41834b305 (via github:kriszyp/node-gyp-build#optional-packages)

**Comment by kriszyp** [comment]
I don't really know what this means, but I assume it has something to do with using a git commit reference as a dep. I published that branch as a separate package in npm and referenced it in msgpackr-extract@v1.1.1. Let me know if that fixes it for you.

**Comment by Owain94** [comment]
@kriszyp I think the latest push (version `1.1.1`) broke the optional dependencies of the package.
The packages below are currently referenced in the latest version, however all the natives are still on `1.1.0` which causes an error when installing packages.

```
optionalDependencies:
    msgpackr-extract-darwin-arm64 "1.1.1"
    msgpackr-extract-darwin-x64 "1.1.1"
    msgpackr-extract-linux-arm "1.1.1"
    msgpackr-extract-linux-arm64 "1.1.1"
    msgpackr-extract-linux-x64 "1.1.1"
    msgpackr-extract-win32-x64 "1.1.1"
```

**Comment by kriszyp** [comment]
Ugh, forgot that I had added an auto-update script to the versions, can you try v1.1.2?

**Comment by Owain94** [comment]
v1.1.2 did indeed fix the error when installing dependencies, thank you!
